// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuBar: typeof import('./src/components/common/MenuBar.vue')['default']
    MessageBox: typeof import('./src/components/common/MessageBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopHeader: typeof import('./src/components/common/TopHeader.vue')['default']
  }
}
